// Thin wrapper around @getalby/sdk's NWCClient for use inside Deno edge functions.
// One client per request — NWC connections are cheap and we don't need pooling.
//
// Configure via the ALBY_NWC_URL secret (a `nostr+walletconnect://...` string
// generated by your Alby Hub under "App Connections").

import { nwc } from "https://esm.sh/@getalby/sdk@4.1.1";

export type NWCMakeInvoiceResult = {
  invoice: string;
  payment_hash: string;
  amount: number;
  expires_at?: number;
};

export type NWCPayInvoiceResult = {
  preimage: string;
  fees_paid?: number;
};

export type NWCLookupInvoiceResult = {
  paid: boolean;
  settled_at?: number;
  amount?: number;
};

export class AlbyNWC {
  private client: nwc.NWCClient;

  constructor(connectionString: string) {
    this.client = new nwc.NWCClient({ nostrWalletConnectUrl: connectionString });
  }

  async makeInvoice(amountSats: number, description: string): Promise<NWCMakeInvoiceResult> {
    const res = await this.client.makeInvoice({
      amount: amountSats * 1000, // NWC uses msats
      description,
    });
    return {
      invoice: res.invoice,
      payment_hash: res.payment_hash,
      amount: Math.round((res.amount ?? 0) / 1000),
      expires_at: res.expires_at,
    };
  }

  async lookupInvoice(paymentHash: string): Promise<NWCLookupInvoiceResult> {
    try {
      const res = await this.client.lookupInvoice({ payment_hash: paymentHash });
      return {
        paid: !!res.settled_at,
        settled_at: res.settled_at,
        amount: res.amount ? Math.round(res.amount / 1000) : undefined,
      };
    } catch (_e) {
      return { paid: false };
    }
  }

  async payInvoice(bolt11: string): Promise<NWCPayInvoiceResult> {
    const res = await this.client.payInvoice({ invoice: bolt11 });
    return { preimage: res.preimage, fees_paid: res.fees_paid };
  }

  close() {
    try { this.client.close(); } catch (_e) { /* ignore */ }
  }
}

export function getAlby(): AlbyNWC | null {
  const url = Deno.env.get("ALBY_NWC_URL");
  if (!url) return null;
  return new AlbyNWC(url);
}
